import { Bookmark, FileText, PanelLeftClose, Minus, Plus, Maximize2, Square } from 'lucide-react'
import PDFThumbnail from './PDFThumbnail'

export default function PDFSidebar({ file, fileUrl, numPages, pageNumber, bookmarks, onSelect, onBookmark, isBookmarked, onClose, readingMode, onReadingMode, scale, onZoom, onFitWidth, onFitPage, theme, onThemeToggle }) {
  return <aside className="sidebar"><div className="sidebar-heading"><div><p className="eyebrow">DOCUMENT</p><h2>{file?.name || 'Untitled document'}</h2></div><button className="icon-button mobile-only" onClick={onClose} aria-label="Close sidebar"><PanelLeftClose size={17} /></button></div>
    {file && <div className="file-meta"><FileText size={15} /><span>{(file.size / 1024 / 1024).toFixed(2)} MB</span><span className="meta-dot" /> <span>{numPages} pages</span></div>}
    <div className="sidebar-section pages-section"><div className="section-label"><span>Pages</span><span>{numPages || '—'}</span></div><div className="thumbnail-list">{fileUrl && Array.from({ length: numPages }, (_, index) => <PDFThumbnail key={index + 1} fileUrl={fileUrl} page={index + 1} selected={pageNumber === index + 1} onSelect={onSelect} />)}</div></div>
    <div className="sidebar-section sidebar-tools"><div className="section-label"><span>Reader mode</span></div><div className="sidebar-mode-grid"><button className={readingMode === 'original' ? 'selected' : ''} onClick={() => onReadingMode('original')}>Original</button><button className={readingMode === 'sepia' ? 'selected' : ''} onClick={() => onReadingMode('sepia')}>Sepia</button><button className={readingMode === 'night' ? 'selected' : ''} onClick={() => onReadingMode('night')}>Night</button></div><div className="section-label sidebar-zoom-label"><span>Zoom</span><span>{Math.round(scale * 100)}%</span></div><div className="sidebar-zoom-row"><button className="icon-button" onClick={() => onZoom(-0.1)} aria-label="Zoom out" title="Zoom out"><Minus size={16} /></button><button className="fit-button" onClick={onFitWidth}><Maximize2 size={14} /> Fit width</button><button className="fit-button" onClick={onFitPage}><Square size={13} /> Fit page</button><button className="icon-button" onClick={() => onZoom(0.1)} aria-label="Zoom in" title="Zoom in"><Plus size={16} /></button></div><div className="section-label sidebar-theme-label"><span>App theme</span><span>{theme === 'dark' ? 'Dark' : 'Light'}</span></div><button className="theme-switch-row" onClick={onThemeToggle}><span className={`theme-swatch ${theme}`} /><span>Switch to {theme === 'dark' ? 'light' : 'dark'} mode</span></button></div>
    <div className="sidebar-section bookmark-section"><div className="section-label"><span>Bookmarks</span><span>{bookmarks.length || '—'}</span></div>{bookmarks.length ? bookmarks.map((page) => <button className="bookmark-row" key={page} onClick={() => onSelect(page)}><Bookmark size={14} fill="currentColor" /><span>Page {page}</span><span className="bookmark-page">{page}</span></button>) : <p className="empty-state">Save pages for quick access with the bookmark button below.</p>}</div>
    <div className="sidebar-footer"><span className="status-dot" /> Local document</div>
  </aside>
}
